/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline_database;
import java.sql.*;

/**
 *
 * @author Michael
 */
public class AdministratorMenuPanel extends javax.swing.JPanel {
    AirlineQueries database;
    javax.swing.JPanel ownerPanel;
    
    /**
     * Creates new form AdministratorMenuPanel
     */
    public AdministratorMenuPanel(AirlineQueries database, javax.swing.JPanel panel) {
        this.database = database;
        this.ownerPanel = panel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminMenuPanel = new javax.swing.JPanel();
        adminMenuTitleLabel = new javax.swing.JLabel();
        addDropFlightMenuButton = new javax.swing.JButton();
        addAirportMenuButton = new javax.swing.JButton();
        updateFaresMenuButton = new javax.swing.JButton();
        createLegInstanceMenuButton = new javax.swing.JButton();
        updateLegInstanceMenuButton = new javax.swing.JButton();
        adminBackButton = new javax.swing.JButton();
        addDropFlightPanel = new javax.swing.JPanel();
        addDropMenuLabel = new javax.swing.JLabel();
        addFlightButton = new javax.swing.JButton();
        addDropBackButton = new javax.swing.JButton();
        addDropFlightNumberPromptLabel = new javax.swing.JLabel();
        addDropAirlineNamePromptLabel = new javax.swing.JLabel();
        addDropWeekdayPromptLabel = new javax.swing.JLabel();
        addDropFlightNumberTextField = new javax.swing.JTextField();
        addDropAirlineTextField = new javax.swing.JTextField();
        addDropWeekdayTextField = new javax.swing.JTextField();
        addDropConfirmPane = new javax.swing.JTextPane();
        dropFlightButton = new javax.swing.JButton();
        addAirportPanel = new javax.swing.JPanel();
        addAirportMenuLabel = new javax.swing.JLabel();
        addAirportAddButton = new javax.swing.JButton();
        addAirportBackButton = new javax.swing.JButton();
        addAirportAirportCodePromptLabel = new javax.swing.JLabel();
        addAirportAirlineNamePromptLabel = new javax.swing.JLabel();
        addAirportCityPromptLabel = new javax.swing.JLabel();
        addAirportAirportCodeTextField = new javax.swing.JTextField();
        addAirportAirportNameTextField = new javax.swing.JTextField();
        addAirportCityTextField = new javax.swing.JTextField();
        addAirportConfirmPane = new javax.swing.JTextPane();
        addAirportStateTextField = new javax.swing.JTextField();
        addAirportStatePromptLabel = new javax.swing.JLabel();
        updateFaresPanel = new javax.swing.JPanel();
        updateFaresMenuLabel = new javax.swing.JLabel();
        updateFaresUpdateButton = new javax.swing.JButton();
        updateFaresBackButton = new javax.swing.JButton();
        updateFaresFlightNumberPromptLabel = new javax.swing.JLabel();
        updateFaresFareCodePromptLabel = new javax.swing.JLabel();
        updateFaresFlightNumberTextField = new javax.swing.JTextField();
        updateFaresFareCodeTextField = new javax.swing.JTextField();
        updateFaresConfirmPane = new javax.swing.JTextPane();
        updateFaresAmountTextField = new javax.swing.JTextField();
        updateFaresAmountPromptLabel = new javax.swing.JLabel();
        updateFaresRestrictionsTextField = new javax.swing.JTextField();
        updateFaresRestrictionsPromptLabel = new javax.swing.JLabel();
        createLegInstancePanel = new javax.swing.JPanel();
        createLegInstanceMenuLabel = new javax.swing.JLabel();
        createLegInstanceCreateButton = new javax.swing.JButton();
        createLegInstanceBackButton = new javax.swing.JButton();
        createLegInstanceFlightNumberPromptLabel = new javax.swing.JLabel();
        createLegInstanceLegNumberPromptLabel = new javax.swing.JLabel();
        createLegInstanceLegDatePromptLabel = new javax.swing.JLabel();
        createLegInstanceFlightNumberTextField = new javax.swing.JTextField();
        createLegInstanceLegNumberTextField = new javax.swing.JTextField();
        createLegInstanceLegDateTextField = new javax.swing.JTextField();
        createLegInstanceConfirmPane = new javax.swing.JTextPane();
        createLegInstanceAvailableSeatsTextField = new javax.swing.JTextField();
        createLegInstanceAvailableSeatsPromptLabel = new javax.swing.JLabel();
        createLegInstanceAirplaneIDTextField = new javax.swing.JTextField();
        createLegInstanceAirplaneIDPromptLabel = new javax.swing.JLabel();
        createLegInstanceDepartureAPCodeTextField = new javax.swing.JTextField();
        createLegInstanceDepartureDatePromptLabel = new javax.swing.JLabel();
        createLegInstanceDepartureTimeTextField = new javax.swing.JTextField();
        createLegInstanceDepartureTimePromptLabel = new javax.swing.JLabel();
        createLegInstanceArrivalAPCodeTextField = new javax.swing.JTextField();
        createLegInstanceArrivalAPCodePromptLabel = new javax.swing.JLabel();
        createLegInstanceArrivalTimeTextField = new javax.swing.JTextField();
        createLegInstanceArrivalTimePromptLabel = new javax.swing.JLabel();
        updateLegInstancePanel = new javax.swing.JPanel();
        updateLegInstanceMenuLabel = new javax.swing.JLabel();
        updateLegInstanceUpdateButton = new javax.swing.JButton();
        updateLegInstanceBackButton = new javax.swing.JButton();
        updateLegInstanceFlightNumberPromptLabel = new javax.swing.JLabel();
        updateLegInstanceLegNumberPromptLabel = new javax.swing.JLabel();
        updateLegInstanceLegDatePromptLabel = new javax.swing.JLabel();
        updateLegInstanceFlightNumberTextField = new javax.swing.JTextField();
        updateLegInstanceLegNumberTextField = new javax.swing.JTextField();
        updateLegInstanceLegDateTextField = new javax.swing.JTextField();
        updateLegInstanceConfirmPane = new javax.swing.JTextPane();
        updateLegInstanceAvailableSeatsTextField = new javax.swing.JTextField();
        updateLegInstanceAvailableSeatsPromptLabel = new javax.swing.JLabel();
        updateLegInstanceAirplaneIDTextField = new javax.swing.JTextField();
        updateLegInstanceAirplaneIDPromptLabel = new javax.swing.JLabel();
        updateLegInstanceDepartureAPCodeTextField = new javax.swing.JTextField();
        updateLegInstanceDepartureDatePromptLabel = new javax.swing.JLabel();
        updateLegInstanceDepartureTimeTextField = new javax.swing.JTextField();
        updateLegInstanceDepartureTimePromptLabel = new javax.swing.JLabel();
        updateLegInstanceArrivalAPCodeTextField = new javax.swing.JTextField();
        updateLegInstanceArrivalAPCodePromptLabel = new javax.swing.JLabel();
        updateLegInstanceArrivalTimeTextField = new javax.swing.JTextField();
        updateLegInstanceArrivalTimePromptLabel = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        adminMenuPanel.setBackground(new java.awt.Color(248, 248, 248));
        adminMenuPanel.setMinimumSize(new java.awt.Dimension(550, 343));

        adminMenuTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        adminMenuTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminMenuTitleLabel.setText("Administrative Menu");

        addDropFlightMenuButton.setText("Add/Drop Flight");
        addDropFlightMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDropFlightMenuButtonActionPerformed(evt);
            }
        });

        addAirportMenuButton.setText("Add Airport");
        addAirportMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAirportMenuButtonActionPerformed(evt);
            }
        });

        updateFaresMenuButton.setText("Update Fares");
        updateFaresMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFaresMenuButtonActionPerformed(evt);
            }
        });

        createLegInstanceMenuButton.setText("Create Leg Instance");
        createLegInstanceMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createLegInstanceMenuButtonActionPerformed(evt);
            }
        });

        updateLegInstanceMenuButton.setText("Update Leg Instance");
        updateLegInstanceMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateLegInstanceMenuButtonActionPerformed(evt);
            }
        });

        adminBackButton.setText("Back");
        adminBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminMenuPanelLayout = new javax.swing.GroupLayout(adminMenuPanel);
        adminMenuPanel.setLayout(adminMenuPanelLayout);
        adminMenuPanelLayout.setHorizontalGroup(
            adminMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminMenuPanelLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(adminMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(adminMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(adminMenuTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(adminMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateLegInstanceMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(createLegInstanceMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateFaresMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addAirportMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addDropFlightMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        adminMenuPanelLayout.setVerticalGroup(
            adminMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminMenuTitleLabel)
                .addGap(65, 65, 65)
                .addComponent(addDropFlightMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addAirportMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateFaresMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createLegInstanceMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateLegInstanceMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(adminBackButton)
                .addContainerGap())
        );

        add(adminMenuPanel, "card5");

        addDropFlightPanel.setBackground(new java.awt.Color(248, 248, 248));
        addDropFlightPanel.setMinimumSize(new java.awt.Dimension(550, 343));
        addDropFlightPanel.setName(""); // NOI18N

        addDropMenuLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addDropMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addDropMenuLabel.setText("Add/Drop Flight");

        addFlightButton.setText("Add");
        addFlightButton.setMaximumSize(new java.awt.Dimension(55, 23));
        addFlightButton.setMinimumSize(new java.awt.Dimension(55, 23));
        addFlightButton.setPreferredSize(new java.awt.Dimension(55, 23));
        addFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightButtonActionPerformed(evt);
            }
        });

        addDropBackButton.setText("Back");
        addDropBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDropBackButtonActionPerformed(evt);
            }
        });

        addDropFlightNumberPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addDropFlightNumberPromptLabel.setText("Flight Number");

        addDropAirlineNamePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addDropAirlineNamePromptLabel.setText("Airline Name");

        addDropWeekdayPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addDropWeekdayPromptLabel.setText("Weekday");

        addDropConfirmPane.setBackground(new java.awt.Color(248, 248, 248));

        dropFlightButton.setText("Drop");
        dropFlightButton.setToolTipText("");
        dropFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropFlightButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addDropFlightPanelLayout = new javax.swing.GroupLayout(addDropFlightPanel);
        addDropFlightPanel.setLayout(addDropFlightPanelLayout);
        addDropFlightPanelLayout.setHorizontalGroup(
            addDropFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDropFlightPanelLayout.createSequentialGroup()
                .addGroup(addDropFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDropFlightPanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(addDropMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 130, Short.MAX_VALUE))
                    .addGroup(addDropFlightPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addDropFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addDropFlightPanelLayout.createSequentialGroup()
                                .addGroup(addDropFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addDropWeekdayPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addDropAirlineNamePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addDropFlightNumberPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addDropFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addDropFlightNumberTextField)
                                    .addComponent(addDropWeekdayTextField)
                                    .addComponent(addDropAirlineTextField)))
                            .addGroup(addDropFlightPanelLayout.createSequentialGroup()
                                .addComponent(addDropConfirmPane)
                                .addGap(10, 10, 10)
                                .addComponent(addDropBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dropFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        addDropFlightPanelLayout.setVerticalGroup(
            addDropFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDropFlightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addDropMenuLabel)
                .addGap(18, 18, 18)
                .addGroup(addDropFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDropFlightNumberPromptLabel)
                    .addComponent(addDropFlightNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addDropFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDropAirlineNamePromptLabel)
                    .addComponent(addDropAirlineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addDropFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDropWeekdayPromptLabel)
                    .addComponent(addDropWeekdayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addGroup(addDropFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDropConfirmPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addDropFlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addDropBackButton)
                        .addComponent(dropFlightButton)
                        .addComponent(addFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        add(addDropFlightPanel, "card6");

        addAirportPanel.setBackground(new java.awt.Color(248, 248, 248));
        addAirportPanel.setMinimumSize(new java.awt.Dimension(550, 343));
        addAirportPanel.setName(""); // NOI18N

        addAirportMenuLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addAirportMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addAirportMenuLabel.setText("Add Airport");

        addAirportAddButton.setText("Add");
        addAirportAddButton.setPreferredSize(new java.awt.Dimension(55, 23));
        addAirportAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAirportAddButtonActionPerformed(evt);
            }
        });

        addAirportBackButton.setText("Back");
        addAirportBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAirportBackButtonActionPerformed(evt);
            }
        });

        addAirportAirportCodePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addAirportAirportCodePromptLabel.setText("Airport Code");

        addAirportAirlineNamePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addAirportAirlineNamePromptLabel.setText("Airport Name");

        addAirportCityPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addAirportCityPromptLabel.setText("City");

        addAirportConfirmPane.setBackground(new java.awt.Color(248, 248, 248));

        addAirportStatePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addAirportStatePromptLabel.setText("State");

        javax.swing.GroupLayout addAirportPanelLayout = new javax.swing.GroupLayout(addAirportPanel);
        addAirportPanel.setLayout(addAirportPanelLayout);
        addAirportPanelLayout.setHorizontalGroup(
            addAirportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAirportPanelLayout.createSequentialGroup()
                .addGroup(addAirportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addAirportPanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(addAirportMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 130, Short.MAX_VALUE))
                    .addGroup(addAirportPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addAirportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addAirportPanelLayout.createSequentialGroup()
                                .addGroup(addAirportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addAirportCityPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addAirportAirlineNamePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addAirportAirportCodePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addAirportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addAirportAirportCodeTextField)
                                    .addComponent(addAirportCityTextField)
                                    .addComponent(addAirportAirportNameTextField)))
                            .addGroup(addAirportPanelLayout.createSequentialGroup()
                                .addComponent(addAirportConfirmPane)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addAirportBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addAirportAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(addAirportPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addAirportStatePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addAirportStateTextField)))
                .addContainerGap())
        );
        addAirportPanelLayout.setVerticalGroup(
            addAirportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addAirportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addAirportMenuLabel)
                .addGap(18, 18, 18)
                .addGroup(addAirportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAirportAirportCodePromptLabel)
                    .addComponent(addAirportAirportCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addAirportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAirportAirlineNamePromptLabel)
                    .addComponent(addAirportAirportNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addAirportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAirportCityPromptLabel)
                    .addComponent(addAirportCityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addAirportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAirportStatePromptLabel)
                    .addComponent(addAirportStateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(addAirportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addAirportConfirmPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addAirportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addAirportAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addAirportBackButton)))
                .addContainerGap())
        );

        add(addAirportPanel, "card6");

        updateFaresPanel.setBackground(new java.awt.Color(248, 248, 248));
        updateFaresPanel.setMinimumSize(new java.awt.Dimension(550, 343));
        updateFaresPanel.setName(""); // NOI18N

        updateFaresMenuLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        updateFaresMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateFaresMenuLabel.setText("Update Fares");

        updateFaresUpdateButton.setText("Update");
        updateFaresUpdateButton.setPreferredSize(new java.awt.Dimension(55, 23));
        updateFaresUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFaresUpdateButtonActionPerformed(evt);
            }
        });

        updateFaresBackButton.setText("Back");
        updateFaresBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFaresBackButtonActionPerformed(evt);
            }
        });

        updateFaresFlightNumberPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateFaresFlightNumberPromptLabel.setText("Flight Number");

        updateFaresFareCodePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateFaresFareCodePromptLabel.setText("Fare Code");

        updateFaresConfirmPane.setBackground(new java.awt.Color(248, 248, 248));

        updateFaresAmountPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateFaresAmountPromptLabel.setText("Amount");

        updateFaresRestrictionsPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateFaresRestrictionsPromptLabel.setText("Restrictions");

        javax.swing.GroupLayout updateFaresPanelLayout = new javax.swing.GroupLayout(updateFaresPanel);
        updateFaresPanel.setLayout(updateFaresPanelLayout);
        updateFaresPanelLayout.setHorizontalGroup(
            updateFaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateFaresPanelLayout.createSequentialGroup()
                .addGroup(updateFaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateFaresPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(updateFaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updateFaresPanelLayout.createSequentialGroup()
                                .addGroup(updateFaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateFaresFareCodePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateFaresFlightNumberPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(updateFaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(updateFaresFlightNumberTextField)
                                    .addComponent(updateFaresFareCodeTextField)))
                            .addGroup(updateFaresPanelLayout.createSequentialGroup()
                                .addComponent(updateFaresConfirmPane)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateFaresBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateFaresUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(updateFaresPanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(updateFaresMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 130, Short.MAX_VALUE))
                    .addGroup(updateFaresPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(updateFaresAmountPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateFaresAmountTextField))
                    .addGroup(updateFaresPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(updateFaresRestrictionsPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateFaresRestrictionsTextField)))
                .addContainerGap())
        );
        updateFaresPanelLayout.setVerticalGroup(
            updateFaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateFaresPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateFaresMenuLabel)
                .addGap(18, 18, 18)
                .addGroup(updateFaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateFaresFlightNumberPromptLabel)
                    .addComponent(updateFaresFlightNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updateFaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateFaresFareCodePromptLabel)
                    .addComponent(updateFaresFareCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updateFaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateFaresAmountPromptLabel)
                    .addComponent(updateFaresAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updateFaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateFaresRestrictionsPromptLabel)
                    .addComponent(updateFaresRestrictionsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(updateFaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateFaresConfirmPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(updateFaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updateFaresUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateFaresBackButton)))
                .addContainerGap())
        );

        add(updateFaresPanel, "card6");

        createLegInstancePanel.setBackground(new java.awt.Color(248, 248, 248));
        createLegInstancePanel.setMinimumSize(new java.awt.Dimension(550, 343));
        createLegInstancePanel.setName(""); // NOI18N

        createLegInstanceMenuLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createLegInstanceMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createLegInstanceMenuLabel.setText("Create Leg Instance");

        createLegInstanceCreateButton.setText("Create");
        createLegInstanceCreateButton.setPreferredSize(new java.awt.Dimension(55, 23));
        createLegInstanceCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createLegInstanceCreateButtonActionPerformed(evt);
            }
        });

        createLegInstanceBackButton.setText("Back");
        createLegInstanceBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createLegInstanceBackButtonActionPerformed(evt);
            }
        });

        createLegInstanceFlightNumberPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createLegInstanceFlightNumberPromptLabel.setText("Flight Number");

        createLegInstanceLegNumberPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createLegInstanceLegNumberPromptLabel.setText("Leg Number");

        createLegInstanceLegDatePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createLegInstanceLegDatePromptLabel.setText("Leg Date");

        createLegInstanceConfirmPane.setBackground(new java.awt.Color(248, 248, 248));

        createLegInstanceAvailableSeatsPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createLegInstanceAvailableSeatsPromptLabel.setText("Available Seats");

        createLegInstanceAirplaneIDPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createLegInstanceAirplaneIDPromptLabel.setText("Airplane ID");

        createLegInstanceDepartureDatePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createLegInstanceDepartureDatePromptLabel.setText("Depart Airport Code");

        createLegInstanceDepartureTimePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createLegInstanceDepartureTimePromptLabel.setText("Departure Time");

        createLegInstanceArrivalAPCodePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createLegInstanceArrivalAPCodePromptLabel.setText("Arrival Airport Code");

        createLegInstanceArrivalTimePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createLegInstanceArrivalTimePromptLabel.setText("Arrival Time");

        javax.swing.GroupLayout createLegInstancePanelLayout = new javax.swing.GroupLayout(createLegInstancePanel);
        createLegInstancePanel.setLayout(createLegInstancePanelLayout);
        createLegInstancePanelLayout.setHorizontalGroup(
            createLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createLegInstancePanelLayout.createSequentialGroup()
                .addGroup(createLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createLegInstancePanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(createLegInstanceMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 130, Short.MAX_VALUE))
                    .addGroup(createLegInstancePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(createLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createLegInstancePanelLayout.createSequentialGroup()
                                .addGroup(createLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createLegInstanceLegDatePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(createLegInstanceLegNumberPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(createLegInstanceFlightNumberPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(createLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(createLegInstanceFlightNumberTextField)
                                    .addComponent(createLegInstanceLegDateTextField)
                                    .addComponent(createLegInstanceLegNumberTextField)))
                            .addGroup(createLegInstancePanelLayout.createSequentialGroup()
                                .addComponent(createLegInstanceConfirmPane)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(createLegInstanceBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createLegInstanceCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(createLegInstancePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(createLegInstanceAvailableSeatsPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createLegInstanceAvailableSeatsTextField))
                    .addGroup(createLegInstancePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(createLegInstanceDepartureDatePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createLegInstanceDepartureAPCodeTextField))
                    .addGroup(createLegInstancePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(createLegInstanceAirplaneIDPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createLegInstanceAirplaneIDTextField))
                    .addGroup(createLegInstancePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(createLegInstanceDepartureTimePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createLegInstanceDepartureTimeTextField))
                    .addGroup(createLegInstancePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(createLegInstanceArrivalAPCodePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createLegInstanceArrivalAPCodeTextField))
                    .addGroup(createLegInstancePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(createLegInstanceArrivalTimePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createLegInstanceArrivalTimeTextField)))
                .addContainerGap())
        );
        createLegInstancePanelLayout.setVerticalGroup(
            createLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createLegInstancePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createLegInstanceMenuLabel)
                .addGap(18, 18, 18)
                .addGroup(createLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createLegInstanceFlightNumberPromptLabel)
                    .addComponent(createLegInstanceFlightNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createLegInstanceLegNumberPromptLabel)
                    .addComponent(createLegInstanceLegNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createLegInstanceLegDatePromptLabel)
                    .addComponent(createLegInstanceLegDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createLegInstanceAvailableSeatsPromptLabel)
                    .addComponent(createLegInstanceAvailableSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createLegInstanceAirplaneIDPromptLabel)
                    .addComponent(createLegInstanceAirplaneIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createLegInstanceDepartureDatePromptLabel)
                    .addComponent(createLegInstanceDepartureAPCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createLegInstanceDepartureTimePromptLabel)
                    .addComponent(createLegInstanceDepartureTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createLegInstanceArrivalAPCodePromptLabel)
                    .addComponent(createLegInstanceArrivalAPCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createLegInstanceArrivalTimePromptLabel)
                    .addComponent(createLegInstanceArrivalTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(createLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createLegInstanceConfirmPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(createLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(createLegInstanceCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(createLegInstanceBackButton)))
                .addContainerGap())
        );

        add(createLegInstancePanel, "card6");

        updateLegInstancePanel.setBackground(new java.awt.Color(248, 248, 248));
        updateLegInstancePanel.setMinimumSize(new java.awt.Dimension(550, 343));
        updateLegInstancePanel.setName(""); // NOI18N

        updateLegInstanceMenuLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        updateLegInstanceMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateLegInstanceMenuLabel.setText("Update Leg Instance");

        updateLegInstanceUpdateButton.setText("Update");
        updateLegInstanceUpdateButton.setPreferredSize(new java.awt.Dimension(55, 23));
        updateLegInstanceUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateLegInstanceUpdateButtonActionPerformed(evt);
            }
        });

        updateLegInstanceBackButton.setText("Back");
        updateLegInstanceBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateLegInstanceBackButtonActionPerformed(evt);
            }
        });

        updateLegInstanceFlightNumberPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateLegInstanceFlightNumberPromptLabel.setText("Flight Number");

        updateLegInstanceLegNumberPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateLegInstanceLegNumberPromptLabel.setText("Leg Number");

        updateLegInstanceLegDatePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateLegInstanceLegDatePromptLabel.setText("Leg Date");

        updateLegInstanceConfirmPane.setBackground(new java.awt.Color(248, 248, 248));

        updateLegInstanceAvailableSeatsPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateLegInstanceAvailableSeatsPromptLabel.setText("Available Seats");

        updateLegInstanceAirplaneIDPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateLegInstanceAirplaneIDPromptLabel.setText("Airplane ID");

        updateLegInstanceDepartureDatePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateLegInstanceDepartureDatePromptLabel.setText("Depart Airport Code");

        updateLegInstanceDepartureTimePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateLegInstanceDepartureTimePromptLabel.setText("Departure Time");

        updateLegInstanceArrivalAPCodePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateLegInstanceArrivalAPCodePromptLabel.setText("Arrival Airport Code");

        updateLegInstanceArrivalTimePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateLegInstanceArrivalTimePromptLabel.setText("Arrival Time");

        javax.swing.GroupLayout updateLegInstancePanelLayout = new javax.swing.GroupLayout(updateLegInstancePanel);
        updateLegInstancePanel.setLayout(updateLegInstancePanelLayout);
        updateLegInstancePanelLayout.setHorizontalGroup(
            updateLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLegInstancePanelLayout.createSequentialGroup()
                .addGroup(updateLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateLegInstancePanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(updateLegInstanceMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 130, Short.MAX_VALUE))
                    .addGroup(updateLegInstancePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(updateLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updateLegInstancePanelLayout.createSequentialGroup()
                                .addGroup(updateLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateLegInstanceLegDatePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateLegInstanceLegNumberPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateLegInstanceFlightNumberPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(updateLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(updateLegInstanceFlightNumberTextField)
                                    .addComponent(updateLegInstanceLegDateTextField)
                                    .addComponent(updateLegInstanceLegNumberTextField)))
                            .addGroup(updateLegInstancePanelLayout.createSequentialGroup()
                                .addComponent(updateLegInstanceConfirmPane)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateLegInstanceBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateLegInstanceUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(updateLegInstancePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(updateLegInstanceAvailableSeatsPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateLegInstanceAvailableSeatsTextField))
                    .addGroup(updateLegInstancePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(updateLegInstanceDepartureDatePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateLegInstanceDepartureAPCodeTextField))
                    .addGroup(updateLegInstancePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(updateLegInstanceAirplaneIDPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateLegInstanceAirplaneIDTextField))
                    .addGroup(updateLegInstancePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(updateLegInstanceDepartureTimePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateLegInstanceDepartureTimeTextField))
                    .addGroup(updateLegInstancePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(updateLegInstanceArrivalAPCodePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateLegInstanceArrivalAPCodeTextField))
                    .addGroup(updateLegInstancePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(updateLegInstanceArrivalTimePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateLegInstanceArrivalTimeTextField)))
                .addContainerGap())
        );
        updateLegInstancePanelLayout.setVerticalGroup(
            updateLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLegInstancePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateLegInstanceMenuLabel)
                .addGap(18, 18, 18)
                .addGroup(updateLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateLegInstanceFlightNumberPromptLabel)
                    .addComponent(updateLegInstanceFlightNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateLegInstanceLegNumberPromptLabel)
                    .addComponent(updateLegInstanceLegNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateLegInstanceLegDatePromptLabel)
                    .addComponent(updateLegInstanceLegDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateLegInstanceAvailableSeatsPromptLabel)
                    .addComponent(updateLegInstanceAvailableSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateLegInstanceAirplaneIDPromptLabel)
                    .addComponent(updateLegInstanceAirplaneIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateLegInstanceDepartureDatePromptLabel)
                    .addComponent(updateLegInstanceDepartureAPCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateLegInstanceDepartureTimePromptLabel)
                    .addComponent(updateLegInstanceDepartureTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateLegInstanceArrivalAPCodePromptLabel)
                    .addComponent(updateLegInstanceArrivalAPCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateLegInstanceArrivalTimePromptLabel)
                    .addComponent(updateLegInstanceArrivalTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(updateLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateLegInstanceConfirmPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(updateLegInstancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updateLegInstanceUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateLegInstanceBackButton)))
                .addContainerGap())
        );

        add(updateLegInstancePanel, "card6");
    }// </editor-fold>//GEN-END:initComponents

    private void adminBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBackButtonActionPerformed
        this.setVisible(false);
        ownerPanel.setVisible(true);
    }//GEN-LAST:event_adminBackButtonActionPerformed

    private void dropFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropFlightButtonActionPerformed
        String flightNumber = addDropFlightNumberTextField.getText();    
        
        String textAreaString = database.dropFlight(flightNumber);
        
        addDropConfirmPane.setText(textAreaString);
    }//GEN-LAST:event_dropFlightButtonActionPerformed

    private void addDropBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDropBackButtonActionPerformed
        addDropFlightPanel.setVisible(false);
        adminMenuPanel.setVisible(true);
    }//GEN-LAST:event_addDropBackButtonActionPerformed

    private void addFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightButtonActionPerformed
        String flightNumber = addDropFlightNumberTextField.getText();
        String airlineName = addDropAirlineTextField.getText();
        String weekday = addDropWeekdayTextField.getText();      
        
        String textAreaString = database.addFlight(flightNumber,
                airlineName, weekday);
        
        addDropConfirmPane.setText(textAreaString);
    }//GEN-LAST:event_addFlightButtonActionPerformed

    private void addAirportAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAirportAddButtonActionPerformed
        String airportCode = addAirportAirportCodeTextField.getText();
        String airportName = addAirportAirportNameTextField.getText();
        String city = addAirportCityTextField.getText();
        String state = addAirportStateTextField.getText();     
        
        String textAreaString = database.addAirport(airportCode,
                airportName, city, state);
        
        addAirportConfirmPane.setText(textAreaString);
    }//GEN-LAST:event_addAirportAddButtonActionPerformed

    private void addAirportBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAirportBackButtonActionPerformed
        addAirportPanel.setVisible(false);
        adminMenuPanel.setVisible(true);
    }//GEN-LAST:event_addAirportBackButtonActionPerformed

    private void updateFaresUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFaresUpdateButtonActionPerformed
        String flightNumber = updateFaresFlightNumberTextField.getText();
        String fareCode = updateFaresFareCodeTextField.getText();       
        String amount = updateFaresAmountTextField.getText();
        String restrictions = updateFaresRestrictionsTextField.getText();
        
        String textAreaString = database.updateFares(flightNumber, fareCode,
                    amount, restrictions);
        
        updateFaresConfirmPane.setText(textAreaString);
    }//GEN-LAST:event_updateFaresUpdateButtonActionPerformed

    private void updateFaresBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFaresBackButtonActionPerformed
        updateFaresPanel.setVisible(false);
        adminMenuPanel.setVisible(true);
    }//GEN-LAST:event_updateFaresBackButtonActionPerformed

    private void createLegInstanceCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createLegInstanceCreateButtonActionPerformed
        String flightNumber = createLegInstanceFlightNumberTextField.getText();
        String legNumber = createLegInstanceLegNumberTextField.getText();
        String legDate = createLegInstanceLegDateTextField.getText();
        String availableSeats = createLegInstanceAvailableSeatsTextField.getText();
        String airplaneID = createLegInstanceAirplaneIDTextField.getText();
        String departAPCode = createLegInstanceDepartureAPCodeTextField.getText();
        String departTime = createLegInstanceDepartureTimeTextField.getText();
        String arrivalAPCode = createLegInstanceArrivalAPCodeTextField.getText();
        String arrivalTime = createLegInstanceArrivalTimeTextField.getText();        
        
        String textAreaString = database.createLegInstance(flightNumber,
                legNumber, legDate, availableSeats, airplaneID,
                departAPCode, departTime, arrivalAPCode, arrivalTime);
        
        createLegInstanceConfirmPane.setText(textAreaString);
    }//GEN-LAST:event_createLegInstanceCreateButtonActionPerformed

    private void createLegInstanceBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createLegInstanceBackButtonActionPerformed
        createLegInstancePanel.setVisible(false);
        adminMenuPanel.setVisible(true);
    }//GEN-LAST:event_createLegInstanceBackButtonActionPerformed

    private void updateLegInstanceUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateLegInstanceUpdateButtonActionPerformed
        String flightNumber = updateLegInstanceFlightNumberTextField.getText();
        String legNumber = updateLegInstanceLegNumberTextField.getText();
        String legDate = updateLegInstanceLegDateTextField.getText();
        String availableSeats = updateLegInstanceAvailableSeatsTextField.getText();
        String airplaneID = updateLegInstanceAirplaneIDTextField.getText();
        String departAPCode = updateLegInstanceDepartureAPCodeTextField.getText();
        String departTime = updateLegInstanceDepartureTimeTextField.getText();
        String arrivalAPCode = updateLegInstanceArrivalAPCodeTextField.getText();
        String arrivalTime = updateLegInstanceArrivalTimeTextField.getText();        
        
        String textAreaString = database.updateLegInstance(flightNumber,
                legNumber, legDate, availableSeats, airplaneID,
                departAPCode, departTime, arrivalAPCode, arrivalTime);
        
        updateLegInstanceConfirmPane.setText(textAreaString);
    }//GEN-LAST:event_updateLegInstanceUpdateButtonActionPerformed

    private void updateLegInstanceBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateLegInstanceBackButtonActionPerformed
        updateLegInstancePanel.setVisible(false);
        adminMenuPanel.setVisible(true);
    }//GEN-LAST:event_updateLegInstanceBackButtonActionPerformed

    private void addDropFlightMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDropFlightMenuButtonActionPerformed
        adminMenuPanel.setVisible(false);
        addDropFlightPanel.setVisible(true);
    }//GEN-LAST:event_addDropFlightMenuButtonActionPerformed

    private void addAirportMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAirportMenuButtonActionPerformed
        adminMenuPanel.setVisible(false);
        addAirportPanel.setVisible(true);
    }//GEN-LAST:event_addAirportMenuButtonActionPerformed

    private void updateFaresMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFaresMenuButtonActionPerformed
        adminMenuPanel.setVisible(false);
        updateFaresPanel.setVisible(true);
    }//GEN-LAST:event_updateFaresMenuButtonActionPerformed

    private void createLegInstanceMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createLegInstanceMenuButtonActionPerformed
        adminMenuPanel.setVisible(false);
        createLegInstancePanel.setVisible(true);
    }//GEN-LAST:event_createLegInstanceMenuButtonActionPerformed

    private void updateLegInstanceMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateLegInstanceMenuButtonActionPerformed
        adminMenuPanel.setVisible(false);
        updateLegInstancePanel.setVisible(true);
    }//GEN-LAST:event_updateLegInstanceMenuButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAirportAddButton;
    private javax.swing.JLabel addAirportAirlineNamePromptLabel;
    private javax.swing.JLabel addAirportAirportCodePromptLabel;
    private javax.swing.JTextField addAirportAirportCodeTextField;
    private javax.swing.JTextField addAirportAirportNameTextField;
    private javax.swing.JButton addAirportBackButton;
    private javax.swing.JLabel addAirportCityPromptLabel;
    private javax.swing.JTextField addAirportCityTextField;
    private javax.swing.JTextPane addAirportConfirmPane;
    private javax.swing.JButton addAirportMenuButton;
    private javax.swing.JLabel addAirportMenuLabel;
    private javax.swing.JPanel addAirportPanel;
    private javax.swing.JLabel addAirportStatePromptLabel;
    private javax.swing.JTextField addAirportStateTextField;
    private javax.swing.JLabel addDropAirlineNamePromptLabel;
    private javax.swing.JTextField addDropAirlineTextField;
    private javax.swing.JButton addDropBackButton;
    private javax.swing.JTextPane addDropConfirmPane;
    private javax.swing.JButton addDropFlightMenuButton;
    private javax.swing.JLabel addDropFlightNumberPromptLabel;
    private javax.swing.JTextField addDropFlightNumberTextField;
    private javax.swing.JPanel addDropFlightPanel;
    private javax.swing.JLabel addDropMenuLabel;
    private javax.swing.JLabel addDropWeekdayPromptLabel;
    private javax.swing.JTextField addDropWeekdayTextField;
    private javax.swing.JButton addFlightButton;
    private javax.swing.JButton adminBackButton;
    private javax.swing.JPanel adminMenuPanel;
    private javax.swing.JLabel adminMenuTitleLabel;
    private javax.swing.JLabel createLegInstanceAirplaneIDPromptLabel;
    private javax.swing.JTextField createLegInstanceAirplaneIDTextField;
    private javax.swing.JLabel createLegInstanceArrivalAPCodePromptLabel;
    private javax.swing.JTextField createLegInstanceArrivalAPCodeTextField;
    private javax.swing.JLabel createLegInstanceArrivalTimePromptLabel;
    private javax.swing.JTextField createLegInstanceArrivalTimeTextField;
    private javax.swing.JLabel createLegInstanceAvailableSeatsPromptLabel;
    private javax.swing.JTextField createLegInstanceAvailableSeatsTextField;
    private javax.swing.JButton createLegInstanceBackButton;
    private javax.swing.JTextPane createLegInstanceConfirmPane;
    private javax.swing.JButton createLegInstanceCreateButton;
    private javax.swing.JTextField createLegInstanceDepartureAPCodeTextField;
    private javax.swing.JLabel createLegInstanceDepartureDatePromptLabel;
    private javax.swing.JLabel createLegInstanceDepartureTimePromptLabel;
    private javax.swing.JTextField createLegInstanceDepartureTimeTextField;
    private javax.swing.JLabel createLegInstanceFlightNumberPromptLabel;
    private javax.swing.JTextField createLegInstanceFlightNumberTextField;
    private javax.swing.JLabel createLegInstanceLegDatePromptLabel;
    private javax.swing.JTextField createLegInstanceLegDateTextField;
    private javax.swing.JLabel createLegInstanceLegNumberPromptLabel;
    private javax.swing.JTextField createLegInstanceLegNumberTextField;
    private javax.swing.JButton createLegInstanceMenuButton;
    private javax.swing.JLabel createLegInstanceMenuLabel;
    private javax.swing.JPanel createLegInstancePanel;
    private javax.swing.JButton dropFlightButton;
    private javax.swing.JLabel updateFaresAmountPromptLabel;
    private javax.swing.JTextField updateFaresAmountTextField;
    private javax.swing.JButton updateFaresBackButton;
    private javax.swing.JTextPane updateFaresConfirmPane;
    private javax.swing.JLabel updateFaresFareCodePromptLabel;
    private javax.swing.JTextField updateFaresFareCodeTextField;
    private javax.swing.JLabel updateFaresFlightNumberPromptLabel;
    private javax.swing.JTextField updateFaresFlightNumberTextField;
    private javax.swing.JButton updateFaresMenuButton;
    private javax.swing.JLabel updateFaresMenuLabel;
    private javax.swing.JPanel updateFaresPanel;
    private javax.swing.JLabel updateFaresRestrictionsPromptLabel;
    private javax.swing.JTextField updateFaresRestrictionsTextField;
    private javax.swing.JButton updateFaresUpdateButton;
    private javax.swing.JLabel updateLegInstanceAirplaneIDPromptLabel;
    private javax.swing.JTextField updateLegInstanceAirplaneIDTextField;
    private javax.swing.JLabel updateLegInstanceArrivalAPCodePromptLabel;
    private javax.swing.JTextField updateLegInstanceArrivalAPCodeTextField;
    private javax.swing.JLabel updateLegInstanceArrivalTimePromptLabel;
    private javax.swing.JTextField updateLegInstanceArrivalTimeTextField;
    private javax.swing.JLabel updateLegInstanceAvailableSeatsPromptLabel;
    private javax.swing.JTextField updateLegInstanceAvailableSeatsTextField;
    private javax.swing.JButton updateLegInstanceBackButton;
    private javax.swing.JTextPane updateLegInstanceConfirmPane;
    private javax.swing.JTextField updateLegInstanceDepartureAPCodeTextField;
    private javax.swing.JLabel updateLegInstanceDepartureDatePromptLabel;
    private javax.swing.JLabel updateLegInstanceDepartureTimePromptLabel;
    private javax.swing.JTextField updateLegInstanceDepartureTimeTextField;
    private javax.swing.JLabel updateLegInstanceFlightNumberPromptLabel;
    private javax.swing.JTextField updateLegInstanceFlightNumberTextField;
    private javax.swing.JLabel updateLegInstanceLegDatePromptLabel;
    private javax.swing.JTextField updateLegInstanceLegDateTextField;
    private javax.swing.JLabel updateLegInstanceLegNumberPromptLabel;
    private javax.swing.JTextField updateLegInstanceLegNumberTextField;
    private javax.swing.JButton updateLegInstanceMenuButton;
    private javax.swing.JLabel updateLegInstanceMenuLabel;
    private javax.swing.JPanel updateLegInstancePanel;
    private javax.swing.JButton updateLegInstanceUpdateButton;
    // End of variables declaration//GEN-END:variables
}
