/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline_database;
import java.sql.*;

/**
 *
 * @author Michael
 */
public class CustomerMenuPanel extends javax.swing.JPanel {
    AirlineQueries database;
    javax.swing.JPanel ownerPanel;
    
    /**
     * Creates new form CustomerMenuPanel
     * 
     * @param conn
     * @param panel
     */
    public CustomerMenuPanel(AirlineQueries database, javax.swing.JPanel panel) {
        this.database = database;
        this.ownerPanel = panel;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerMenuPanel = new javax.swing.JPanel();
        customerMenuTitleLabel = new javax.swing.JLabel();
        makeReservationMenuButton = new javax.swing.JButton();
        cancelReservationMenuButton = new javax.swing.JButton();
        confirmReservationMenuButton = new javax.swing.JButton();
        printTripItineraryMenuButton = new javax.swing.JButton();
        locateFareMenuButton = new javax.swing.JButton();
        customerBackButton = new javax.swing.JButton();
        makeReservationPanel = new javax.swing.JPanel();
        makeReservationMenuLabel = new javax.swing.JLabel();
        makeReservationCreateButton = new javax.swing.JButton();
        makeReservationBackButton = new javax.swing.JButton();
        flightNumberPromptLabel = new javax.swing.JLabel();
        legNumberPromptLabel = new javax.swing.JLabel();
        departureDatePromptLabel = new javax.swing.JLabel();
        seatNumberPromptLabel = new javax.swing.JLabel();
        customerNamePromptLabel = new javax.swing.JLabel();
        customerPhonePromptLabel = new javax.swing.JLabel();
        flightNumberTextField = new javax.swing.JTextField();
        legNumberTextField = new javax.swing.JTextField();
        departureDateTextField = new javax.swing.JTextField();
        seatNumberTextField = new javax.swing.JTextField();
        customerNameTextField = new javax.swing.JTextField();
        customerPhoneTextField = new javax.swing.JTextField();
        makeResConfirmPane = new javax.swing.JTextPane();
        cancelReservationPanel = new javax.swing.JPanel();
        cancelReservationMenuLabel = new javax.swing.JLabel();
        cancelReservationDeleteButton = new javax.swing.JButton();
        cancelReservationBackButton = new javax.swing.JButton();
        cancelFlightNumberPromptLabel = new javax.swing.JLabel();
        cancelLegNumberPromptLabel = new javax.swing.JLabel();
        cancelCustomerNamePromptLabel = new javax.swing.JLabel();
        cancelCustomerPhonePromptLabel = new javax.swing.JLabel();
        cancelFlightNumberTextField = new javax.swing.JTextField();
        cancelLegNumberTextField = new javax.swing.JTextField();
        cancelCustomerNameTextField = new javax.swing.JTextField();
        cancelCustomerPhoneTextField = new javax.swing.JTextField();
        cancelResConfirmPane = new javax.swing.JTextPane();
        confirmReservationPanel = new javax.swing.JPanel();
        confirmReservationMenuLabel = new javax.swing.JLabel();
        confirmReservationConfirmButton = new javax.swing.JButton();
        confirmReservationBackButton = new javax.swing.JButton();
        confirmReservationCustomerNamePromptLabel = new javax.swing.JLabel();
        confirmReservationCustomerPhonePromptLabel = new javax.swing.JLabel();
        confirmReservationFlightNumberTextField = new javax.swing.JTextField();
        confirmReservationLegNumberTextField = new javax.swing.JTextField();
        confirmReservationConfirmPane = new javax.swing.JTextPane();
        confirmReservationScrollPane = new javax.swing.JScrollPane();
        confirmReservationTextPane = new javax.swing.JTextPane();
        confirmReservationCustomerPhonePromptLabel1 = new javax.swing.JLabel();
        confirmReservationSeatNumberTextField = new javax.swing.JTextField();
        printFlightItineraryPanel = new javax.swing.JPanel();
        printFlightItineraryLabel = new javax.swing.JLabel();
        printFlightItinerarySearchButton = new javax.swing.JButton();
        printFlightItineraryBackButton = new javax.swing.JButton();
        printFlightItineraryCustomerNamePromptLabel = new javax.swing.JLabel();
        printFlightItineraryCustomerNameTextField = new javax.swing.JTextField();
        printFlightItineraryPhoneNumberPromptLabel = new javax.swing.JLabel();
        printFlightItineraryPhoneNumberTextField = new javax.swing.JTextField();
        printFlightItineraryScrollPane = new javax.swing.JScrollPane();
        printFlightItineraryTextArea = new javax.swing.JTextArea();
        printFlightItineraryConfirmPane = new javax.swing.JTextPane();
        locateFarePanel = new javax.swing.JPanel();
        locateFareMenuLabel = new javax.swing.JLabel();
        locateFareSearchButton = new javax.swing.JButton();
        locateFareBackButton = new javax.swing.JButton();
        locateFareFlightNumberPrompt = new javax.swing.JLabel();
        locateFareLegNumberPrompt = new javax.swing.JLabel();
        locateFareFlightNumberTextField = new javax.swing.JTextField();
        locateFareFareCodeTextField = new javax.swing.JTextField();
        locateFareConfirmPanel = new javax.swing.JTextPane();
        locateFareScrollPane = new javax.swing.JScrollPane();
        locateFareTextPane = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(248, 248, 248));
        setLayout(new java.awt.CardLayout());

        customerMenuPanel.setBackground(new java.awt.Color(248, 248, 248));
        customerMenuPanel.setMinimumSize(new java.awt.Dimension(550, 343));

        customerMenuTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        customerMenuTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerMenuTitleLabel.setText("Customer Menu");

        makeReservationMenuButton.setText("Make Reservation");
        makeReservationMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeReservationMenuButtonActionPerformed(evt);
            }
        });

        cancelReservationMenuButton.setText("Cancel Reservation");
        cancelReservationMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelReservationMenuButtonActionPerformed(evt);
            }
        });

        confirmReservationMenuButton.setText("Confirm Reservation");
        confirmReservationMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmReservationMenuButtonActionPerformed(evt);
            }
        });

        printTripItineraryMenuButton.setText("Print Trip Itinerary");
        printTripItineraryMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printTripItineraryMenuButtonActionPerformed(evt);
            }
        });

        locateFareMenuButton.setText("Locate Fare");
        locateFareMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locateFareMenuButtonActionPerformed(evt);
            }
        });

        customerBackButton.setText("Back");
        customerBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerMenuPanelLayout = new javax.swing.GroupLayout(customerMenuPanel);
        customerMenuPanel.setLayout(customerMenuPanelLayout);
        customerMenuPanelLayout.setHorizontalGroup(
            customerMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerMenuPanelLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(customerMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(customerMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(customerMenuTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(customerMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(locateFareMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(printTripItineraryMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(confirmReservationMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(cancelReservationMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(makeReservationMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        customerMenuPanelLayout.setVerticalGroup(
            customerMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerMenuTitleLabel)
                .addGap(65, 65, 65)
                .addComponent(makeReservationMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelReservationMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmReservationMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printTripItineraryMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locateFareMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(customerBackButton)
                .addContainerGap())
        );

        add(customerMenuPanel, "card3");

        makeReservationPanel.setBackground(new java.awt.Color(248, 248, 248));
        makeReservationPanel.setMinimumSize(new java.awt.Dimension(550, 343));
        makeReservationPanel.setName(""); // NOI18N
        makeReservationPanel.setPreferredSize(new java.awt.Dimension(550, 343));

        makeReservationMenuLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        makeReservationMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        makeReservationMenuLabel.setText("Make a Reservation");

        makeReservationCreateButton.setText("Create");
        makeReservationCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeReservationCreateButtonActionPerformed(evt);
            }
        });

        makeReservationBackButton.setText("Back");
        makeReservationBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeReservationBackButtonActionPerformed(evt);
            }
        });

        flightNumberPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        flightNumberPromptLabel.setText("Flight Number");

        legNumberPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legNumberPromptLabel.setText("Leg Number");

        departureDatePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        departureDatePromptLabel.setText("Departure Date");

        seatNumberPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seatNumberPromptLabel.setText("Seat Number");

        customerNamePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        customerNamePromptLabel.setText("Customer Name");

        customerPhonePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        customerPhonePromptLabel.setText("Customer Phone");

        makeResConfirmPane.setBackground(new java.awt.Color(248, 248, 248));

        javax.swing.GroupLayout makeReservationPanelLayout = new javax.swing.GroupLayout(makeReservationPanel);
        makeReservationPanel.setLayout(makeReservationPanelLayout);
        makeReservationPanelLayout.setHorizontalGroup(
            makeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(makeReservationPanelLayout.createSequentialGroup()
                .addGroup(makeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(makeReservationPanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(makeReservationMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(makeReservationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(makeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerPhonePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerNamePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatNumberPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flightNumberPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(legNumberPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departureDatePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(makeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(seatNumberTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(departureDateTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(legNumberTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(flightNumberTextField)
                            .addComponent(customerPhoneTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, makeReservationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(makeResConfirmPane)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(makeReservationBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(makeReservationCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        makeReservationPanelLayout.setVerticalGroup(
            makeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, makeReservationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(makeReservationMenuLabel)
                .addGap(18, 18, 18)
                .addGroup(makeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightNumberPromptLabel)
                    .addComponent(flightNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(makeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(legNumberPromptLabel)
                    .addComponent(legNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(makeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departureDatePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departureDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(makeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatNumberPromptLabel)
                    .addComponent(seatNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(makeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNamePromptLabel)
                    .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(makeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerPhonePromptLabel)
                    .addComponent(customerPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(makeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(makeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(makeReservationCreateButton)
                        .addComponent(makeReservationBackButton))
                    .addComponent(makeResConfirmPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(makeReservationPanel, "card6");

        cancelReservationPanel.setBackground(new java.awt.Color(248, 248, 248));
        cancelReservationPanel.setMinimumSize(new java.awt.Dimension(550, 343));
        cancelReservationPanel.setPreferredSize(new java.awt.Dimension(550, 343));

        cancelReservationMenuLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cancelReservationMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelReservationMenuLabel.setText("Cancel Reservation");

        cancelReservationDeleteButton.setText("Delete");
        cancelReservationDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelReservationDeleteButtonActionPerformed(evt);
            }
        });

        cancelReservationBackButton.setText("Back");
        cancelReservationBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelReservationBackButtonActionPerformed(evt);
            }
        });

        cancelFlightNumberPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelFlightNumberPromptLabel.setText("Flight Number");

        cancelLegNumberPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelLegNumberPromptLabel.setText("Leg Number");

        cancelCustomerNamePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelCustomerNamePromptLabel.setText("Customer Name");

        cancelCustomerPhonePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelCustomerPhonePromptLabel.setText("Customer Phone");

        cancelResConfirmPane.setEditable(false);
        cancelResConfirmPane.setBackground(new java.awt.Color(248, 248, 248));

        javax.swing.GroupLayout cancelReservationPanelLayout = new javax.swing.GroupLayout(cancelReservationPanel);
        cancelReservationPanel.setLayout(cancelReservationPanelLayout);
        cancelReservationPanelLayout.setHorizontalGroup(
            cancelReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancelReservationPanelLayout.createSequentialGroup()
                .addGroup(cancelReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cancelReservationPanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(cancelReservationMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cancelReservationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(cancelReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelCustomerPhonePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelCustomerNamePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelFlightNumberPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelLegNumberPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(cancelReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelCustomerNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cancelCustomerPhoneTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cancelLegNumberTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cancelFlightNumberTextField)))
                    .addGroup(cancelReservationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cancelResConfirmPane)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelReservationBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelReservationDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        cancelReservationPanelLayout.setVerticalGroup(
            cancelReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelReservationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelReservationMenuLabel)
                .addGap(18, 18, 18)
                .addGroup(cancelReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelFlightNumberPromptLabel)
                    .addComponent(cancelFlightNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cancelReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelLegNumberPromptLabel)
                    .addComponent(cancelLegNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cancelReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelCustomerNamePromptLabel)
                    .addComponent(cancelCustomerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cancelReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelCustomerPhonePromptLabel)
                    .addComponent(cancelCustomerPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(cancelReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cancelReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancelReservationDeleteButton)
                        .addComponent(cancelReservationBackButton))
                    .addComponent(cancelResConfirmPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(cancelReservationPanel, "card8");

        confirmReservationPanel.setBackground(new java.awt.Color(248, 248, 248));

        confirmReservationMenuLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        confirmReservationMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmReservationMenuLabel.setText("Confirm a Reservation");

        confirmReservationConfirmButton.setText("Confirm");
        confirmReservationConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmReservationConfirmButtonActionPerformed(evt);
            }
        });

        confirmReservationBackButton.setText("Back");
        confirmReservationBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmReservationBackButtonActionPerformed(evt);
            }
        });

        confirmReservationCustomerNamePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmReservationCustomerNamePromptLabel.setText("Flight Number");

        confirmReservationCustomerPhonePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmReservationCustomerPhonePromptLabel.setText("Leg Number");

        confirmReservationConfirmPane.setBackground(new java.awt.Color(248, 248, 248));

        confirmReservationScrollPane.setViewportView(confirmReservationTextPane);

        confirmReservationCustomerPhonePromptLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmReservationCustomerPhonePromptLabel1.setText("Seat Number");

        javax.swing.GroupLayout confirmReservationPanelLayout = new javax.swing.GroupLayout(confirmReservationPanel);
        confirmReservationPanel.setLayout(confirmReservationPanelLayout);
        confirmReservationPanelLayout.setHorizontalGroup(
            confirmReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmReservationPanelLayout.createSequentialGroup()
                .addGroup(confirmReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(confirmReservationPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmReservationMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(confirmReservationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(confirmReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(confirmReservationPanelLayout.createSequentialGroup()
                                .addGroup(confirmReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmReservationCustomerPhonePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(confirmReservationCustomerNamePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(confirmReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmReservationFlightNumberTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(confirmReservationLegNumberTextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmReservationPanelLayout.createSequentialGroup()
                                .addComponent(confirmReservationConfirmPane, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(confirmReservationBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmReservationConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(confirmReservationScrollPane)
                            .addGroup(confirmReservationPanelLayout.createSequentialGroup()
                                .addComponent(confirmReservationCustomerPhonePromptLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(confirmReservationSeatNumberTextField)))))
                .addContainerGap())
        );
        confirmReservationPanelLayout.setVerticalGroup(
            confirmReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmReservationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(confirmReservationMenuLabel)
                .addGap(18, 18, 18)
                .addGroup(confirmReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmReservationCustomerNamePromptLabel)
                    .addComponent(confirmReservationFlightNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confirmReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmReservationCustomerPhonePromptLabel)
                    .addComponent(confirmReservationLegNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confirmReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmReservationCustomerPhonePromptLabel1)
                    .addComponent(confirmReservationSeatNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmReservationScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confirmReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(confirmReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(confirmReservationConfirmButton)
                        .addComponent(confirmReservationBackButton))
                    .addComponent(confirmReservationConfirmPane, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(confirmReservationPanel, "card8");

        printFlightItineraryPanel.setBackground(new java.awt.Color(248, 248, 248));
        printFlightItineraryPanel.setMinimumSize(new java.awt.Dimension(550, 343));
        printFlightItineraryPanel.setName(""); // NOI18N

        printFlightItineraryLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        printFlightItineraryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        printFlightItineraryLabel.setText("Flight Itinerary");

        printFlightItinerarySearchButton.setText("Search");
        printFlightItinerarySearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printFlightItinerarySearchButtonActionPerformed(evt);
            }
        });

        printFlightItineraryBackButton.setText("Back");
        printFlightItineraryBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printFlightItineraryBackButtonActionPerformed(evt);
            }
        });

        printFlightItineraryCustomerNamePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printFlightItineraryCustomerNamePromptLabel.setText("Customer Name");

        printFlightItineraryPhoneNumberPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printFlightItineraryPhoneNumberPromptLabel.setText("Phone Number");

        printFlightItineraryTextArea.setEditable(false);
        printFlightItineraryTextArea.setColumns(20);
        printFlightItineraryTextArea.setRows(5);
        printFlightItineraryScrollPane.setViewportView(printFlightItineraryTextArea);

        printFlightItineraryConfirmPane.setBackground(new java.awt.Color(248, 248, 248));

        javax.swing.GroupLayout printFlightItineraryPanelLayout = new javax.swing.GroupLayout(printFlightItineraryPanel);
        printFlightItineraryPanel.setLayout(printFlightItineraryPanelLayout);
        printFlightItineraryPanelLayout.setHorizontalGroup(
            printFlightItineraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printFlightItineraryPanelLayout.createSequentialGroup()
                .addGroup(printFlightItineraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(printFlightItineraryPanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(printFlightItineraryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 130, Short.MAX_VALUE))
                    .addGroup(printFlightItineraryPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(printFlightItineraryCustomerNamePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(printFlightItineraryCustomerNameTextField))
                    .addGroup(printFlightItineraryPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(printFlightItineraryScrollPane))
                    .addGroup(printFlightItineraryPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(printFlightItineraryPhoneNumberPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(printFlightItineraryPhoneNumberTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printFlightItineraryPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(printFlightItineraryConfirmPane)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printFlightItineraryBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printFlightItinerarySearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        printFlightItineraryPanelLayout.setVerticalGroup(
            printFlightItineraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printFlightItineraryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(printFlightItineraryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(printFlightItineraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printFlightItineraryCustomerNamePromptLabel)
                    .addComponent(printFlightItineraryCustomerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(printFlightItineraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printFlightItineraryPhoneNumberPromptLabel)
                    .addComponent(printFlightItineraryPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printFlightItineraryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(printFlightItineraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(printFlightItineraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(printFlightItinerarySearchButton)
                        .addComponent(printFlightItineraryBackButton))
                    .addComponent(printFlightItineraryConfirmPane, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(printFlightItineraryPanel, "card6");

        locateFarePanel.setBackground(new java.awt.Color(248, 248, 248));
        locateFarePanel.setMinimumSize(new java.awt.Dimension(550, 343));

        locateFareMenuLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        locateFareMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        locateFareMenuLabel.setText("Locate Fare");

        locateFareSearchButton.setText("Confirm");
        locateFareSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locateFareSearchButtonActionPerformed(evt);
            }
        });

        locateFareBackButton.setText("Back");
        locateFareBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locateFareBackButtonActionPerformed(evt);
            }
        });

        locateFareFlightNumberPrompt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        locateFareFlightNumberPrompt.setText("Flight Number");

        locateFareLegNumberPrompt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        locateFareLegNumberPrompt.setText("Fare Code");

        locateFareConfirmPanel.setBackground(new java.awt.Color(248, 248, 248));

        locateFareScrollPane.setViewportView(locateFareTextPane);

        javax.swing.GroupLayout locateFarePanelLayout = new javax.swing.GroupLayout(locateFarePanel);
        locateFarePanel.setLayout(locateFarePanelLayout);
        locateFarePanelLayout.setHorizontalGroup(
            locateFarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locateFarePanelLayout.createSequentialGroup()
                .addGroup(locateFarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(locateFarePanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(locateFareMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(locateFarePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(locateFarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(locateFareFlightNumberPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locateFareLegNumberPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(locateFarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(locateFareFareCodeTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(locateFareFlightNumberTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, locateFarePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(locateFareConfirmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(locateFareBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(locateFareSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(locateFarePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(locateFareScrollPane)))
                .addContainerGap())
        );
        locateFarePanelLayout.setVerticalGroup(
            locateFarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locateFarePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(locateFareMenuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(locateFarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locateFareFlightNumberPrompt)
                    .addComponent(locateFareFlightNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(locateFarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locateFareLegNumberPrompt)
                    .addComponent(locateFareFareCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(locateFareScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(locateFarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, locateFarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(locateFareSearchButton)
                        .addComponent(locateFareBackButton))
                    .addComponent(locateFareConfirmPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(locateFarePanel, "card8");
    }// </editor-fold>//GEN-END:initComponents

    private void makeReservationMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeReservationMenuButtonActionPerformed
        customerMenuPanel.setVisible(false);
        makeReservationPanel.setVisible(true);
    }//GEN-LAST:event_makeReservationMenuButtonActionPerformed

    private void customerBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBackButtonActionPerformed
        this.setVisible(false);
        ownerPanel.setVisible(true);
    }//GEN-LAST:event_customerBackButtonActionPerformed

    private void makeReservationCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeReservationCreateButtonActionPerformed
        String flightNumber = flightNumberTextField.getText();
        String legNumber = legNumberTextField.getText();
        String departureDate = departureDateTextField.getText();
        String seatNumber = seatNumberTextField.getText();
        String customerName = customerNameTextField.getText();
        String customerPhone = customerPhoneTextField.getText();

        String textAreaString = database.makeReservation(flightNumber, legNumber,
            departureDate, seatNumber, customerName, customerPhone);
        
        makeResConfirmPane.setText(textAreaString);
    }//GEN-LAST:event_makeReservationCreateButtonActionPerformed

    private void makeReservationBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeReservationBackButtonActionPerformed
        makeReservationPanel.setVisible(false);
        customerMenuPanel.setVisible(true);
    }//GEN-LAST:event_makeReservationBackButtonActionPerformed

    private void cancelReservationDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelReservationDeleteButtonActionPerformed
        String flightNumber = cancelFlightNumberTextField.getText();
        String legNumber = cancelLegNumberTextField.getText();
        String customerName = cancelCustomerNameTextField.getText();
        String customerNumber = cancelCustomerPhoneTextField.getText();
        
        String textAreaString = database.cancelReservation(flightNumber, legNumber, customerName, customerNumber);
        
        cancelResConfirmPane.setText(textAreaString);
    }//GEN-LAST:event_cancelReservationDeleteButtonActionPerformed

    private void cancelReservationBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelReservationBackButtonActionPerformed
        cancelReservationPanel.setVisible(false);
        customerMenuPanel.setVisible(true);
    }//GEN-LAST:event_cancelReservationBackButtonActionPerformed

    private void locateFareSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locateFareSearchButtonActionPerformed
        String flightNum = locateFareFlightNumberTextField.getText();
        String fareCode = locateFareFareCodeTextField.getText();
        
        String textAreaString = database.locateFare(flightNum, fareCode);
        
        locateFareTextPane.setText(textAreaString);
    }//GEN-LAST:event_locateFareSearchButtonActionPerformed

    private void locateFareBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locateFareBackButtonActionPerformed
        locateFarePanel.setVisible(false);
        customerMenuPanel.setVisible(true);
    }//GEN-LAST:event_locateFareBackButtonActionPerformed

    private void printFlightItinerarySearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printFlightItinerarySearchButtonActionPerformed
        String customerName = printFlightItineraryCustomerNameTextField.getText();
        String customerNumber = printFlightItineraryPhoneNumberTextField.getText();
        
        String textAreaString = database.printFlightItinerary(customerName, customerNumber);
        
        printFlightItineraryTextArea.setText(textAreaString);
    }//GEN-LAST:event_printFlightItinerarySearchButtonActionPerformed

    private void printFlightItineraryBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printFlightItineraryBackButtonActionPerformed
        printFlightItineraryPanel.setVisible(false);
        customerMenuPanel.setVisible(true);
    }//GEN-LAST:event_printFlightItineraryBackButtonActionPerformed

    private void cancelReservationMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelReservationMenuButtonActionPerformed
        customerMenuPanel.setVisible(false);
        cancelReservationPanel.setVisible(true);
    }//GEN-LAST:event_cancelReservationMenuButtonActionPerformed

    private void confirmReservationMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmReservationMenuButtonActionPerformed
        customerMenuPanel.setVisible(false);
        confirmReservationPanel.setVisible(true);
    }//GEN-LAST:event_confirmReservationMenuButtonActionPerformed

    private void printTripItineraryMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printTripItineraryMenuButtonActionPerformed
        customerMenuPanel.setVisible(false);
        printFlightItineraryPanel.setVisible(true);
    }//GEN-LAST:event_printTripItineraryMenuButtonActionPerformed

    private void locateFareMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locateFareMenuButtonActionPerformed
        customerMenuPanel.setVisible(false);
        locateFarePanel.setVisible(true);
    }//GEN-LAST:event_locateFareMenuButtonActionPerformed

    private void confirmReservationBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmReservationBackButtonActionPerformed
        confirmReservationPanel.setVisible(false);
        customerMenuPanel.setVisible(true);
    }//GEN-LAST:event_confirmReservationBackButtonActionPerformed

    private void confirmReservationConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmReservationConfirmButtonActionPerformed
        String flightNumber = confirmReservationFlightNumberTextField.getText();
        String legNumber = confirmReservationLegNumberTextField.getText();
        String seatNumber = confirmReservationSeatNumberTextField.getText();

        String textAreaString = database.confirmReservation(flightNumber, legNumber, seatNumber);

        confirmReservationTextPane.setText(textAreaString);
    }//GEN-LAST:event_confirmReservationConfirmButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancelCustomerNamePromptLabel;
    private javax.swing.JTextField cancelCustomerNameTextField;
    private javax.swing.JLabel cancelCustomerPhonePromptLabel;
    private javax.swing.JTextField cancelCustomerPhoneTextField;
    private javax.swing.JLabel cancelFlightNumberPromptLabel;
    private javax.swing.JTextField cancelFlightNumberTextField;
    private javax.swing.JLabel cancelLegNumberPromptLabel;
    private javax.swing.JTextField cancelLegNumberTextField;
    private javax.swing.JTextPane cancelResConfirmPane;
    private javax.swing.JButton cancelReservationBackButton;
    private javax.swing.JButton cancelReservationDeleteButton;
    private javax.swing.JButton cancelReservationMenuButton;
    private javax.swing.JLabel cancelReservationMenuLabel;
    private javax.swing.JPanel cancelReservationPanel;
    private javax.swing.JButton confirmReservationBackButton;
    private javax.swing.JButton confirmReservationConfirmButton;
    private javax.swing.JTextPane confirmReservationConfirmPane;
    private javax.swing.JLabel confirmReservationCustomerNamePromptLabel;
    private javax.swing.JLabel confirmReservationCustomerPhonePromptLabel;
    private javax.swing.JLabel confirmReservationCustomerPhonePromptLabel1;
    private javax.swing.JTextField confirmReservationFlightNumberTextField;
    private javax.swing.JTextField confirmReservationLegNumberTextField;
    private javax.swing.JButton confirmReservationMenuButton;
    private javax.swing.JLabel confirmReservationMenuLabel;
    private javax.swing.JPanel confirmReservationPanel;
    private javax.swing.JScrollPane confirmReservationScrollPane;
    private javax.swing.JTextField confirmReservationSeatNumberTextField;
    private javax.swing.JTextPane confirmReservationTextPane;
    private javax.swing.JButton customerBackButton;
    private javax.swing.JPanel customerMenuPanel;
    private javax.swing.JLabel customerMenuTitleLabel;
    private javax.swing.JLabel customerNamePromptLabel;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JLabel customerPhonePromptLabel;
    private javax.swing.JTextField customerPhoneTextField;
    private javax.swing.JLabel departureDatePromptLabel;
    private javax.swing.JTextField departureDateTextField;
    private javax.swing.JLabel flightNumberPromptLabel;
    private javax.swing.JTextField flightNumberTextField;
    private javax.swing.JLabel legNumberPromptLabel;
    private javax.swing.JTextField legNumberTextField;
    private javax.swing.JButton locateFareBackButton;
    private javax.swing.JTextPane locateFareConfirmPanel;
    private javax.swing.JTextField locateFareFareCodeTextField;
    private javax.swing.JLabel locateFareFlightNumberPrompt;
    private javax.swing.JTextField locateFareFlightNumberTextField;
    private javax.swing.JLabel locateFareLegNumberPrompt;
    private javax.swing.JButton locateFareMenuButton;
    private javax.swing.JLabel locateFareMenuLabel;
    private javax.swing.JPanel locateFarePanel;
    private javax.swing.JScrollPane locateFareScrollPane;
    private javax.swing.JButton locateFareSearchButton;
    private javax.swing.JTextPane locateFareTextPane;
    private javax.swing.JTextPane makeResConfirmPane;
    private javax.swing.JButton makeReservationBackButton;
    private javax.swing.JButton makeReservationCreateButton;
    private javax.swing.JButton makeReservationMenuButton;
    private javax.swing.JLabel makeReservationMenuLabel;
    private javax.swing.JPanel makeReservationPanel;
    private javax.swing.JButton printFlightItineraryBackButton;
    private javax.swing.JTextPane printFlightItineraryConfirmPane;
    private javax.swing.JLabel printFlightItineraryCustomerNamePromptLabel;
    private javax.swing.JTextField printFlightItineraryCustomerNameTextField;
    private javax.swing.JLabel printFlightItineraryLabel;
    private javax.swing.JPanel printFlightItineraryPanel;
    private javax.swing.JLabel printFlightItineraryPhoneNumberPromptLabel;
    private javax.swing.JTextField printFlightItineraryPhoneNumberTextField;
    private javax.swing.JScrollPane printFlightItineraryScrollPane;
    private javax.swing.JButton printFlightItinerarySearchButton;
    private javax.swing.JTextArea printFlightItineraryTextArea;
    private javax.swing.JButton printTripItineraryMenuButton;
    private javax.swing.JLabel seatNumberPromptLabel;
    private javax.swing.JTextField seatNumberTextField;
    // End of variables declaration//GEN-END:variables
}
