package airline_database;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Michael
 */
public class MainAirlineWindow extends javax.swing.JFrame {
    AirlineQueries database;
    
    /**
     * Creates new form Airline_Main_Interface
     */
    public MainAirlineWindow(AirlineQueries database) {
        initComponents();
        
        this.database = database;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        databaseMenu = new javax.swing.JMenu();
        saveTransactionsMenuOption = new javax.swing.JMenuItem();
        rollbackTransactionsMenuOption = new javax.swing.JMenuItem();
        quitMenuOption = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Airline Database");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(200, 100, 750, 513));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(560, 440));
        setPreferredSize(new java.awt.Dimension(560, 440));
        getContentPane().setLayout(new java.awt.CardLayout());

        databaseMenu.setText("Database");

        saveTransactionsMenuOption.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveTransactionsMenuOption.setText("Save Transactions");
        saveTransactionsMenuOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTransactionsMenuOptionActionPerformed(evt);
            }
        });
        databaseMenu.add(saveTransactionsMenuOption);

        rollbackTransactionsMenuOption.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        rollbackTransactionsMenuOption.setText("RollBack Transactions");
        rollbackTransactionsMenuOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollbackTransactionsMenuOptionActionPerformed(evt);
            }
        });
        databaseMenu.add(rollbackTransactionsMenuOption);

        quitMenuOption.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        quitMenuOption.setText("Quit");
        quitMenuOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitMenuOptionActionPerformed(evt);
            }
        });
        databaseMenu.add(quitMenuOption);

        menuBar.add(databaseMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void quitMenuOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitMenuOptionActionPerformed
        SaveChangePopup x = new SaveChangePopup(database);
        x.setVisible(true);
    }//GEN-LAST:event_quitMenuOptionActionPerformed

    private void saveTransactionsMenuOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTransactionsMenuOptionActionPerformed
        database.saveTransactions();
        database.beginTransactionProcessing();
    }//GEN-LAST:event_saveTransactionsMenuOptionActionPerformed

    private void rollbackTransactionsMenuOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollbackTransactionsMenuOptionActionPerformed
        database.rollbackTransactions();
        database.beginTransactionProcessing();
    }//GEN-LAST:event_rollbackTransactionsMenuOptionActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu databaseMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem quitMenuOption;
    private javax.swing.JMenuItem rollbackTransactionsMenuOption;
    private javax.swing.JMenuItem saveTransactionsMenuOption;
    // End of variables declaration//GEN-END:variables
}
