/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline_database;
import java.awt.Color;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Michael
 */
public class MainMenuPanel extends javax.swing.JPanel {
    AirlineQueries database;
    javax.swing.JFrame ownerFrame;
    CustomerMenuPanel customerMenuPanel;
    ReportingMenuPanel reportingMenuPanel;
    AdministratorMenuPanel adminMenuPanel;
    javax.swing.JPanel contentPane;
    
    /**
     * Creates new form MainMenuPanel
     */
    public MainMenuPanel(AirlineQueries database, javax.swing.JFrame frame) {
        this.database = database;
        this.ownerFrame = frame;
                
        initComponents();
        
        contentPane = new javax.swing.JPanel();
        contentPane.setLayout(new BoxLayout(contentPane, BoxLayout.Y_AXIS));
        contentPane.setBackground(new Color(248,248,248));
        
        customerMenuPanel = new CustomerMenuPanel(database, mainMenuPanel);
        reportingMenuPanel = new ReportingMenuPanel(database, mainMenuPanel);
        adminMenuPanel = new AdministratorMenuPanel(database, mainMenuPanel);
        
        contentPane.add(mainMenuPanel, "card1");
        contentPane.add(customerMenuPanel, "card2");
        contentPane.add(reportingMenuPanel, "card3");
        contentPane.add(adminMenuPanel, "card4");        
        
        mainMenuPanel.setVisible(true);
        customerMenuPanel.setVisible(false);
        reportingMenuPanel.setVisible(false);
        adminMenuPanel.setVisible(false);
        
        ownerFrame.getContentPane().add(contentPane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuPanel = new javax.swing.JPanel();
        mainMenuTitleLabel = new javax.swing.JLabel();
        customerMenuButton = new javax.swing.JButton();
        reportingMenuButton = new javax.swing.JButton();
        administrativeMenuButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(248, 248, 248));

        mainMenuPanel.setBackground(new java.awt.Color(248, 248, 248));
        mainMenuPanel.setMinimumSize(new java.awt.Dimension(550, 343));

        mainMenuTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mainMenuTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuTitleLabel.setText("Main Menu");

        customerMenuButton.setText("Customer Functions");
        customerMenuButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        customerMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerMenuButtonActionPerformed(evt);
            }
        });

        reportingMenuButton.setText("Reporting Functions");
        reportingMenuButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reportingMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportingMenuButtonActionPerformed(evt);
            }
        });

        administrativeMenuButton.setText("Administrative Functions");
        administrativeMenuButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        administrativeMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administrativeMenuButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.setAlignmentY(0.0F);
        quitButton.setHideActionText(true);
        quitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        quitButton.setName(""); // NOI18N
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuPanelLayout = new javax.swing.GroupLayout(mainMenuPanel);
        mainMenuPanel.setLayout(mainMenuPanelLayout);
        mainMenuPanelLayout.setHorizontalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(quitButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(customerMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(administrativeMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainMenuTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reportingMenuButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        mainMenuPanelLayout.setVerticalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMenuTitleLabel)
                .addGap(97, 97, 97)
                .addComponent(customerMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportingMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(administrativeMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quitButton)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void customerMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerMenuButtonActionPerformed
        mainMenuPanel.setVisible(false);
        customerMenuPanel.setVisible(true);
    }//GEN-LAST:event_customerMenuButtonActionPerformed

    private void reportingMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportingMenuButtonActionPerformed
        mainMenuPanel.setVisible(false);
        reportingMenuPanel.setVisible(true);
    }//GEN-LAST:event_reportingMenuButtonActionPerformed

    private void administrativeMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administrativeMenuButtonActionPerformed
        mainMenuPanel.setVisible(false);
        adminMenuPanel.setVisible(true);
    }//GEN-LAST:event_administrativeMenuButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        SaveChangePopup x = new SaveChangePopup(database);
        x.setVisible(true);
    }//GEN-LAST:event_quitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton administrativeMenuButton;
    private javax.swing.JButton customerMenuButton;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JLabel mainMenuTitleLabel;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton reportingMenuButton;
    // End of variables declaration//GEN-END:variables
}
