/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline_database;
import java.sql.*;

/**
 *
 * @author Michael
 */
public class ReportingMenuPanel extends javax.swing.JPanel {
    AirlineQueries database;
    javax.swing.JPanel ownerPanel;
    
    /**
     * Creates new form ReportingMenuPanel
     */
    public ReportingMenuPanel(AirlineQueries database, javax.swing.JPanel panel) {
        this.database = database;
        this.ownerPanel = panel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportingMenuPanel = new javax.swing.JPanel();
        reportingMenuTitleLabel = new javax.swing.JLabel();
        printFlightRosterMenuButton = new javax.swing.JButton();
        printFlightScheduleMenuButton = new javax.swing.JButton();
        printFlightPerformanceReportMenuButton = new javax.swing.JButton();
        reportingBackButton = new javax.swing.JButton();
        printFlightRosterPanel = new javax.swing.JPanel();
        printFlightRosterLabel = new javax.swing.JLabel();
        printFlightRosterSearchButton = new javax.swing.JButton();
        printFlightRosterBackButton = new javax.swing.JButton();
        printFlightRosterFlightNumberPromptLabel = new javax.swing.JLabel();
        printFlightRosterFlightNumberTextField = new javax.swing.JTextField();
        printFlightRosterScrollPane = new javax.swing.JScrollPane();
        printFlightRosterTextArea = new javax.swing.JTextArea();
        printFlightRosterConfirmPane = new javax.swing.JTextPane();
        printFlightSchedulePanel = new javax.swing.JPanel();
        printFlightScheduleLabel = new javax.swing.JLabel();
        printFlightScheduleCreateButton = new javax.swing.JButton();
        printFlightScheduleBackButton = new javax.swing.JButton();
        printFlightScheduleFlightNumberPromptLabel = new javax.swing.JLabel();
        printFlightScheduleFlightNumberTextField = new javax.swing.JTextField();
        printFlightScheduleConfirmPane = new javax.swing.JTextPane();
        printFlightScheduleScrollPane = new javax.swing.JScrollPane();
        printFlightScheduleTextArea = new javax.swing.JTextArea();
        printFlightPerformanceReportPanel = new javax.swing.JPanel();
        printFlightPerformanceReportLabel = new javax.swing.JLabel();
        printFlightPerformanceReportSearchButton = new javax.swing.JButton();
        printFlightPerformanceReportBackButton = new javax.swing.JButton();
        printFlightPerformanceReportAirlinePromptLabel = new javax.swing.JLabel();
        printFlightPerformanceReportAirlineTextField = new javax.swing.JTextField();
        printFlightPerformanceReportDelayedScrollPane = new javax.swing.JScrollPane();
        printFlightPerformanceReportDelayedTextArea = new javax.swing.JTextArea();
        printFlightPerformanceReportOnTimeScrollPane = new javax.swing.JScrollPane();
        printFlightPerformanceReportOnTimeTextArea = new javax.swing.JTextArea();
        printFlightPerformanceReportOnTimeLabel = new javax.swing.JLabel();
        printFlightPerformanceReportDelayedLabel = new javax.swing.JLabel();
        printFlightPerformanceReportConfirmPane = new javax.swing.JTextPane();

        setLayout(new java.awt.CardLayout());

        reportingMenuPanel.setBackground(new java.awt.Color(248, 248, 248));
        reportingMenuPanel.setMinimumSize(new java.awt.Dimension(550, 343));

        reportingMenuTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        reportingMenuTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportingMenuTitleLabel.setText("Reporting Menu");

        printFlightRosterMenuButton.setText("Print Flight Roster");
        printFlightRosterMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printFlightRosterMenuButtonActionPerformed(evt);
            }
        });

        printFlightScheduleMenuButton.setText("Print Flight Schedule");
        printFlightScheduleMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printFlightScheduleMenuButtonActionPerformed(evt);
            }
        });

        printFlightPerformanceReportMenuButton.setText("Print Flight Performance Report");
        printFlightPerformanceReportMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printFlightPerformanceReportMenuButtonActionPerformed(evt);
            }
        });

        reportingBackButton.setText("Back");
        reportingBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportingBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reportingMenuPanelLayout = new javax.swing.GroupLayout(reportingMenuPanel);
        reportingMenuPanel.setLayout(reportingMenuPanelLayout);
        reportingMenuPanelLayout.setHorizontalGroup(
            reportingMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportingMenuPanelLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(reportingMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reportingBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(reportingMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(reportingMenuTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(reportingMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(printFlightPerformanceReportMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(printFlightScheduleMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(printFlightRosterMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        reportingMenuPanelLayout.setVerticalGroup(
            reportingMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportingMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportingMenuTitleLabel)
                .addGap(94, 94, 94)
                .addComponent(printFlightRosterMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printFlightScheduleMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printFlightPerformanceReportMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(reportingBackButton)
                .addContainerGap())
        );

        add(reportingMenuPanel, "card4");

        printFlightRosterPanel.setBackground(new java.awt.Color(248, 248, 248));
        printFlightRosterPanel.setMinimumSize(new java.awt.Dimension(550, 343));
        printFlightRosterPanel.setName(""); // NOI18N
        printFlightRosterPanel.setPreferredSize(new java.awt.Dimension(550, 343));

        printFlightRosterLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        printFlightRosterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        printFlightRosterLabel.setText("Flight Roster");

        printFlightRosterSearchButton.setText("Search");
        printFlightRosterSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printFlightRosterSearchButtonActionPerformed(evt);
            }
        });

        printFlightRosterBackButton.setText("Back");
        printFlightRosterBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printFlightRosterBackButtonActionPerformed(evt);
            }
        });

        printFlightRosterFlightNumberPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printFlightRosterFlightNumberPromptLabel.setText("Flight Number");

        printFlightRosterTextArea.setEditable(false);
        printFlightRosterTextArea.setColumns(20);
        printFlightRosterTextArea.setRows(5);
        printFlightRosterScrollPane.setViewportView(printFlightRosterTextArea);

        printFlightRosterConfirmPane.setBackground(new java.awt.Color(248, 248, 248));

        javax.swing.GroupLayout printFlightRosterPanelLayout = new javax.swing.GroupLayout(printFlightRosterPanel);
        printFlightRosterPanel.setLayout(printFlightRosterPanelLayout);
        printFlightRosterPanelLayout.setHorizontalGroup(
            printFlightRosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printFlightRosterPanelLayout.createSequentialGroup()
                .addGroup(printFlightRosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(printFlightRosterPanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(printFlightRosterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(printFlightRosterPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(printFlightRosterFlightNumberPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(printFlightRosterFlightNumberTextField))
                    .addGroup(printFlightRosterPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(printFlightRosterScrollPane))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printFlightRosterPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(printFlightRosterConfirmPane, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printFlightRosterBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printFlightRosterSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        printFlightRosterPanelLayout.setVerticalGroup(
            printFlightRosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printFlightRosterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(printFlightRosterLabel)
                .addGap(18, 18, 18)
                .addGroup(printFlightRosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printFlightRosterFlightNumberPromptLabel)
                    .addComponent(printFlightRosterFlightNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printFlightRosterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(printFlightRosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(printFlightRosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(printFlightRosterSearchButton)
                        .addComponent(printFlightRosterBackButton))
                    .addComponent(printFlightRosterConfirmPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(printFlightRosterPanel, "card6");

        printFlightSchedulePanel.setBackground(new java.awt.Color(248, 248, 248));
        printFlightSchedulePanel.setMinimumSize(new java.awt.Dimension(550, 343));
        printFlightSchedulePanel.setName(""); // NOI18N
        printFlightSchedulePanel.setPreferredSize(new java.awt.Dimension(550, 343));

        printFlightScheduleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        printFlightScheduleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        printFlightScheduleLabel.setText("Flight Schedule");

        printFlightScheduleCreateButton.setText("Search");
        printFlightScheduleCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printFlightScheduleCreateButtonActionPerformed(evt);
            }
        });

        printFlightScheduleBackButton.setText("Back");
        printFlightScheduleBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printFlightScheduleBackButtonActionPerformed(evt);
            }
        });

        printFlightScheduleFlightNumberPromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printFlightScheduleFlightNumberPromptLabel.setText("Flight Number");

        printFlightScheduleConfirmPane.setBackground(new java.awt.Color(248, 248, 248));

        printFlightScheduleTextArea.setEditable(false);
        printFlightScheduleTextArea.setColumns(20);
        printFlightScheduleTextArea.setRows(5);
        printFlightScheduleScrollPane.setViewportView(printFlightScheduleTextArea);

        javax.swing.GroupLayout printFlightSchedulePanelLayout = new javax.swing.GroupLayout(printFlightSchedulePanel);
        printFlightSchedulePanel.setLayout(printFlightSchedulePanelLayout);
        printFlightSchedulePanelLayout.setHorizontalGroup(
            printFlightSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printFlightSchedulePanelLayout.createSequentialGroup()
                .addGroup(printFlightSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(printFlightSchedulePanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(printFlightScheduleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(printFlightSchedulePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(printFlightSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(printFlightSchedulePanelLayout.createSequentialGroup()
                                .addComponent(printFlightScheduleFlightNumberPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(printFlightScheduleFlightNumberTextField))
                            .addGroup(printFlightSchedulePanelLayout.createSequentialGroup()
                                .addComponent(printFlightScheduleConfirmPane, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(printFlightScheduleBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(printFlightScheduleCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(printFlightSchedulePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(printFlightScheduleScrollPane)))
                .addContainerGap())
        );
        printFlightSchedulePanelLayout.setVerticalGroup(
            printFlightSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printFlightSchedulePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(printFlightScheduleLabel)
                .addGap(18, 18, 18)
                .addGroup(printFlightSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printFlightScheduleFlightNumberPromptLabel)
                    .addComponent(printFlightScheduleFlightNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(printFlightScheduleScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(printFlightSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(printFlightSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(printFlightScheduleCreateButton)
                        .addComponent(printFlightScheduleBackButton))
                    .addComponent(printFlightScheduleConfirmPane))
                .addContainerGap())
        );

        add(printFlightSchedulePanel, "card6");

        printFlightPerformanceReportPanel.setBackground(new java.awt.Color(248, 248, 248));
        printFlightPerformanceReportPanel.setMinimumSize(new java.awt.Dimension(550, 343));
        printFlightPerformanceReportPanel.setName(""); // NOI18N
        printFlightPerformanceReportPanel.setPreferredSize(new java.awt.Dimension(550, 343));

        printFlightPerformanceReportLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        printFlightPerformanceReportLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        printFlightPerformanceReportLabel.setText("Flight Performance Report");

        printFlightPerformanceReportSearchButton.setText("Search");
        printFlightPerformanceReportSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printFlightPerformanceReportSearchButtonActionPerformed(evt);
            }
        });

        printFlightPerformanceReportBackButton.setText("Back");
        printFlightPerformanceReportBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printFlightPerformanceReportBackButtonActionPerformed(evt);
            }
        });

        printFlightPerformanceReportAirlinePromptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printFlightPerformanceReportAirlinePromptLabel.setText("Airline");

        printFlightPerformanceReportDelayedScrollPane.setPreferredSize(new java.awt.Dimension(166, 75));

        printFlightPerformanceReportDelayedTextArea.setEditable(false);
        printFlightPerformanceReportDelayedTextArea.setColumns(20);
        printFlightPerformanceReportDelayedTextArea.setRows(5);
        printFlightPerformanceReportDelayedTextArea.setPreferredSize(new java.awt.Dimension(164, 74));
        printFlightPerformanceReportDelayedScrollPane.setViewportView(printFlightPerformanceReportDelayedTextArea);

        printFlightPerformanceReportOnTimeScrollPane.setPreferredSize(new java.awt.Dimension(166, 75));

        printFlightPerformanceReportOnTimeTextArea.setEditable(false);
        printFlightPerformanceReportOnTimeTextArea.setColumns(20);
        printFlightPerformanceReportOnTimeTextArea.setRows(5);
        printFlightPerformanceReportOnTimeTextArea.setPreferredSize(new java.awt.Dimension(164, 74));
        printFlightPerformanceReportOnTimeScrollPane.setViewportView(printFlightPerformanceReportOnTimeTextArea);

        printFlightPerformanceReportOnTimeLabel.setText("On-Time");

        printFlightPerformanceReportDelayedLabel.setText("Delayed");

        printFlightPerformanceReportConfirmPane.setBackground(new java.awt.Color(248, 248, 248));

        javax.swing.GroupLayout printFlightPerformanceReportPanelLayout = new javax.swing.GroupLayout(printFlightPerformanceReportPanel);
        printFlightPerformanceReportPanel.setLayout(printFlightPerformanceReportPanelLayout);
        printFlightPerformanceReportPanelLayout.setHorizontalGroup(
            printFlightPerformanceReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printFlightPerformanceReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(printFlightPerformanceReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(printFlightPerformanceReportPanelLayout.createSequentialGroup()
                        .addComponent(printFlightPerformanceReportAirlinePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(printFlightPerformanceReportAirlineTextField))
                    .addComponent(printFlightPerformanceReportDelayedScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(printFlightPerformanceReportOnTimeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(printFlightPerformanceReportPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(printFlightPerformanceReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(printFlightPerformanceReportOnTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(printFlightPerformanceReportDelayedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printFlightPerformanceReportPanelLayout.createSequentialGroup()
                        .addComponent(printFlightPerformanceReportConfirmPane)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printFlightPerformanceReportBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printFlightPerformanceReportSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(printFlightPerformanceReportPanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(printFlightPerformanceReportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        printFlightPerformanceReportPanelLayout.setVerticalGroup(
            printFlightPerformanceReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printFlightPerformanceReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(printFlightPerformanceReportLabel)
                .addGap(18, 18, 18)
                .addGroup(printFlightPerformanceReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printFlightPerformanceReportAirlinePromptLabel)
                    .addComponent(printFlightPerformanceReportAirlineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printFlightPerformanceReportOnTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(printFlightPerformanceReportOnTimeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printFlightPerformanceReportDelayedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printFlightPerformanceReportDelayedScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(printFlightPerformanceReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(printFlightPerformanceReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(printFlightPerformanceReportSearchButton)
                        .addComponent(printFlightPerformanceReportBackButton))
                    .addComponent(printFlightPerformanceReportConfirmPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(printFlightPerformanceReportPanel, "card6");
    }// </editor-fold>//GEN-END:initComponents

    private void printFlightScheduleMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printFlightScheduleMenuButtonActionPerformed
        reportingMenuPanel.setVisible(false);
        printFlightSchedulePanel.setVisible(true);
    }//GEN-LAST:event_printFlightScheduleMenuButtonActionPerformed

    private void printFlightPerformanceReportMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printFlightPerformanceReportMenuButtonActionPerformed
        reportingMenuPanel.setVisible(false);
        printFlightPerformanceReportPanel.setVisible(true);
    }//GEN-LAST:event_printFlightPerformanceReportMenuButtonActionPerformed

    private void reportingBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportingBackButtonActionPerformed
        this.setVisible(false);
        ownerPanel.setVisible(true);
    }//GEN-LAST:event_reportingBackButtonActionPerformed

    private void printFlightRosterSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printFlightRosterSearchButtonActionPerformed
        String FlightNum = printFlightRosterFlightNumberTextField.getText();
        String textAreaString = database.printFlightRoster(FlightNum);
        
        printFlightRosterTextArea.setText(textAreaString);
    }//GEN-LAST:event_printFlightRosterSearchButtonActionPerformed

    private void printFlightRosterBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printFlightRosterBackButtonActionPerformed
        printFlightRosterPanel.setVisible(false);
        reportingMenuPanel.setVisible(true);
    }//GEN-LAST:event_printFlightRosterBackButtonActionPerformed

    private void printFlightScheduleCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printFlightScheduleCreateButtonActionPerformed
        String userFlightNum = printFlightScheduleFlightNumberTextField.getText();
        String textAreaString = database.printFlightSchedule(userFlightNum);
        
        printFlightScheduleTextArea.setText(textAreaString);
    }//GEN-LAST:event_printFlightScheduleCreateButtonActionPerformed

    private void printFlightScheduleBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printFlightScheduleBackButtonActionPerformed
        printFlightSchedulePanel.setVisible(false);
        reportingMenuPanel.setVisible(true);
    }//GEN-LAST:event_printFlightScheduleBackButtonActionPerformed

    private void printFlightPerformanceReportSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printFlightPerformanceReportSearchButtonActionPerformed
        String flightNumber = printFlightPerformanceReportAirlineTextField.getText();  
        
        String textAreaStringOnTime = database.printFlightPerformanceReportOnTime(flightNumber);
        String textAreaStringDelayed = database.printFlightPerformanceReportDelayed(flightNumber);
        
        printFlightPerformanceReportOnTimeTextArea.setText(textAreaStringOnTime);
        printFlightPerformanceReportDelayedTextArea.setText(textAreaStringDelayed);
    }//GEN-LAST:event_printFlightPerformanceReportSearchButtonActionPerformed

    private void printFlightPerformanceReportBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printFlightPerformanceReportBackButtonActionPerformed
        printFlightPerformanceReportPanel.setVisible(false);
        reportingMenuPanel.setVisible(true);
    }//GEN-LAST:event_printFlightPerformanceReportBackButtonActionPerformed

    private void printFlightRosterMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printFlightRosterMenuButtonActionPerformed
        reportingMenuPanel.setVisible(false);
        printFlightRosterPanel.setVisible(true);
    }//GEN-LAST:event_printFlightRosterMenuButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel printFlightPerformanceReportAirlinePromptLabel;
    private javax.swing.JTextField printFlightPerformanceReportAirlineTextField;
    private javax.swing.JButton printFlightPerformanceReportBackButton;
    private javax.swing.JTextPane printFlightPerformanceReportConfirmPane;
    private javax.swing.JLabel printFlightPerformanceReportDelayedLabel;
    private javax.swing.JScrollPane printFlightPerformanceReportDelayedScrollPane;
    private javax.swing.JTextArea printFlightPerformanceReportDelayedTextArea;
    private javax.swing.JLabel printFlightPerformanceReportLabel;
    private javax.swing.JButton printFlightPerformanceReportMenuButton;
    private javax.swing.JLabel printFlightPerformanceReportOnTimeLabel;
    private javax.swing.JScrollPane printFlightPerformanceReportOnTimeScrollPane;
    private javax.swing.JTextArea printFlightPerformanceReportOnTimeTextArea;
    private javax.swing.JPanel printFlightPerformanceReportPanel;
    private javax.swing.JButton printFlightPerformanceReportSearchButton;
    private javax.swing.JButton printFlightRosterBackButton;
    private javax.swing.JTextPane printFlightRosterConfirmPane;
    private javax.swing.JLabel printFlightRosterFlightNumberPromptLabel;
    private javax.swing.JTextField printFlightRosterFlightNumberTextField;
    private javax.swing.JLabel printFlightRosterLabel;
    private javax.swing.JButton printFlightRosterMenuButton;
    private javax.swing.JPanel printFlightRosterPanel;
    private javax.swing.JScrollPane printFlightRosterScrollPane;
    private javax.swing.JButton printFlightRosterSearchButton;
    private javax.swing.JTextArea printFlightRosterTextArea;
    private javax.swing.JButton printFlightScheduleBackButton;
    private javax.swing.JTextPane printFlightScheduleConfirmPane;
    private javax.swing.JButton printFlightScheduleCreateButton;
    private javax.swing.JLabel printFlightScheduleFlightNumberPromptLabel;
    private javax.swing.JTextField printFlightScheduleFlightNumberTextField;
    private javax.swing.JLabel printFlightScheduleLabel;
    private javax.swing.JButton printFlightScheduleMenuButton;
    private javax.swing.JPanel printFlightSchedulePanel;
    private javax.swing.JScrollPane printFlightScheduleScrollPane;
    private javax.swing.JTextArea printFlightScheduleTextArea;
    private javax.swing.JButton reportingBackButton;
    private javax.swing.JPanel reportingMenuPanel;
    private javax.swing.JLabel reportingMenuTitleLabel;
    // End of variables declaration//GEN-END:variables
}
