/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline_database;

/**
 *
 * @author Michael
 */
public class SaveChangePopup extends javax.swing.JFrame {
    private final AirlineQueries database;
    
    /**
     * Creates new form SaveChangePopup
     */
    public SaveChangePopup(AirlineQueries database) {
        initComponents();
        
        this.database = database;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quitDialog = new javax.swing.JPanel();
        quitDialogMainLabel = new javax.swing.JLabel();
        commitTransactionButton = new javax.swing.JButton();
        rollbackTransactionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Save Dialog");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(248, 248, 248));
        setBounds(new java.awt.Rectangle(500, 200, 283, 120));
        setPreferredSize(new java.awt.Dimension(283, 120));
        setResizable(false);

        quitDialogMainLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quitDialogMainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quitDialogMainLabel.setText("Save Changes");

        commitTransactionButton.setText("Save");
        commitTransactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commitTransactionButtonActionPerformed(evt);
            }
        });

        rollbackTransactionButton.setText("Don't Save");
        rollbackTransactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollbackTransactionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout quitDialogLayout = new javax.swing.GroupLayout(quitDialog);
        quitDialog.setLayout(quitDialogLayout);
        quitDialogLayout.setHorizontalGroup(
            quitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quitDialogLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(quitDialogMainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(quitDialogLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(rollbackTransactionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(commitTransactionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        quitDialogLayout.setVerticalGroup(
            quitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quitDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quitDialogMainLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(quitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commitTransactionButton)
                    .addComponent(rollbackTransactionButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(quitDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 99, Short.MAX_VALUE)
                .addComponent(quitDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void commitTransactionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commitTransactionButtonActionPerformed
        database.saveTransactions();
        database.quit();
    }//GEN-LAST:event_commitTransactionButtonActionPerformed

    private void rollbackTransactionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollbackTransactionButtonActionPerformed
        database.rollbackTransactions();
        database.quit();
    }//GEN-LAST:event_rollbackTransactionButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton commitTransactionButton;
    private javax.swing.JPanel quitDialog;
    private javax.swing.JLabel quitDialogMainLabel;
    private javax.swing.JButton rollbackTransactionButton;
    // End of variables declaration//GEN-END:variables
}
